### ISSUE TITLE
Ability to add new fields not only from constructor

### ISSUE THREAD

**Issue by tekord** [acelot/automapper#1]
Hi! Thanks for nice library. I have a mapper which I'd like to complete with some fileds dynamically, but I can't because it has to be set only through the AutoMapper constructor. I think it would be nice if autommaper can provide addField method or something like that.

Thanks!

**Comment by acelot** [comment]
Hi, @tekord! You can add field dynamically via `->withField` method. Note that this method is immutable and returns the new instance of Automapper.

```php
$m = new Automapper(...$fields);
$m = $m->withField(field('newfield', from('anotherfield')));
// Here you can use your updated Automapper.
```
